# Generated by Django 3.0.4 on 2020-04-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('listar', 'listar'),)},
        ),
    ]
