# Generated by Django 3.0.4 on 2020-04-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0004_auto_20200331_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cv',
        ),
    ]
