# Generated by Django 3.0.4 on 2020-04-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0005_delete_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='carga_cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ceduala', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=5)),
                ('foto', models.FileField(upload_to='Foto/%Y/%m/%d')),
                ('idioma', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=15)),
                ('estado_laboral', models.CharField(max_length=20)),
                ('salario', models.IntegerField()),
                ('archivo_cv', models.FileField(upload_to='Cv/%Y/%m/%d')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Departamento')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Cargo')),
                ('experiencia_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Exp_Profesional')),
                ('formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Formacion')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Tipo_Identificacion')),
            ],
        ),
    ]
