# Generated by Django 3.0.4 on 2020-04-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0009_auto_20200407_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Cargo'),
        ),
        migrations.DeleteModel(
            name='Exp_Profesional',
        ),
    ]
