# Generated by Django 3.0.4 on 2020-04-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0010_auto_20200407_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carga_cv',
        ),
    ]
