# Generated by Django 3.0.4 on 2020-04-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0012_carga_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carguecv.Cargo'),
            preserve_default=False,
        ),
    ]
