# Generated by Django 3.0.4 on 2020-04-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0013_carga_cv_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga_cv',
            name='estado_laboral',
        ),
        migrations.RemoveField(
            model_name='carga_cv',
            name='licencia',
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Cargo'),
        ),
    ]
