# Generated by Django 3.0.4 on 2020-04-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0016_auto_20200407_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga_cv',
            name='Departamento',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='municipio',
        ),
        migrations.AddField(
            model_name='carga_cv',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carguecv.Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carguecv.Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carga_cv',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Cargo'),
        ),
    ]
