# Generated by Django 3.0.4 on 2020-03-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Areas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Centro_educativo', models.CharField(max_length=200)),
                ('Nivel_educativo', models.CharField(max_length=200)),
                ('Estado_estudio', models.CharField(max_length=100)),
                ('Periodo_inicio', models.DateField()),
                ('Periodo_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_identificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exp_Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=200)),
                ('Periodo_inicio', models.DateField()),
                ('Periodo_fin', models.DateField()),
                ('Funciones', models.CharField(max_length=300)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Municipio'),
        ),
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ceduala', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=5)),
                ('foto', models.FileField(upload_to='Foto/%Y/%m/%d')),
                ('idioma', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=15)),
                ('estado_laboral', models.CharField(max_length=20)),
                ('salario', models.IntegerField()),
                ('carga_cv', models.FileField(upload_to='Cv/%Y/%m/%d')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Departamento')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Area')),
                ('experiencia_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Exp_Profesional')),
                ('formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Formacion')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carguecv.Tipo_Identificacion')),
            ],
        ),
    ]
