# Generated by Django 3.0.4 on 2020-04-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carguecv', '0003_remove_cv_carga_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='archivo_cv',
            field=models.FileField(default=1, upload_to='Cv/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carguecv.Cargo'),
            preserve_default=False,
        ),
    ]
